---

- name: Install yum utils
  yum:
    name: yum-utils
    state: latest

- name: Add repository hashicop repo
  get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install consul
  yum:
    name: consul
    state: latest

- name: "server is true uncomment"
  replace: 
    path: /etc/consul.d/consul.hcl
    regexp: "#server = true"
    replace: "server = true"

- name: "bootstrap expect uncomment"
  replace: 
    path: /etc/consul.d/consul.hcl
    regexp: "#bootstrap_expect=3"
    replace: "bootstrap_expect=1"

- name: "bind addr to ip"
  lineinfile:
    path: /etc/consul.d/consul.hcl
    line: bind_addr = "${ansible_private_network.ipv4.address}"

- name: Enable consul
  service:
    name: consul
    enabled: yes

- name: Start consul
  service:
    name: consul
    state: started
    

