---
- name: Install yum utils
  yum:
    name: yum-utils
    state: latest

- name: Add repository hashicop repo
  get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install nomad
  yum:
    name: nomad
    state: latest
  

